version: '3'

volumes:
  db-data:
  app-vendor:
  app-tmp:
  app-log:
  app-git:
  redis:
  bundle:
  node_modules:


services:
  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    volumes:
      - '.:/product-register'
      - 'bundle:/usr/local/bundle:cached'
      - 'node_modules:/product-register/node_modules'
      - 'app-vendor:/product-register/vendor'
      - 'app-tmp:/product-register/tmp'
      - 'app-log:/product-register/log'
      - 'app-git:/product-register/.git'
    environment:
      - 'DATABASE_PASSWORD=postgres'
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis
    links:
      - db
  
  db:
    image: postgres
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
  
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - redis:/data


